services:
  postgres:
    image: postgres:16
    container_name: meteo-postgres
    restart: always
    environment:
      POSTGRES_DB: meteo
      POSTGRES_USER: meteo_user
      POSTGRES_PASSWORD: meteo_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/initdb:/docker-entrypoint-initdb.d:ro
      - ./docker/ranks:/ranks:ro


volumes:
  postgres_data:
    driver: local
